### ISSUE TITLE
pressing issues going forward (31/5/17)

### ISSUE THREAD

**Issue by mattlub** [FACN1/nazareth-events#94]
### priority 1
- [x] style event detail page #85
- [ ] display something when no events on a date? #92
- [x] style the header #97 
- [x] events on same date should be sorted by start time #91 

### priority 2
- [ ] 'load more' button at the bottom of the events list

### priority 1
- [ ] create a logout
- [ ] img url on event form #93 

### priority 2
- [ ] ability to add recurring events- a different form for creating a recurring event #68
- [ ] how to create login credentials (one-time link to a form to create an account?)
- [ ] style login page and add event forms
- [ ] Dashboard page for organiser (e.g. buttons for create event, create recurring event, see my events)
- [ ] My events page: A page that lists all of the events that belong to the organiser, its design will be similar to the home page. The page must give the organiser the ability to manage their events ( it must at least have a button to delete an event)

## demoted to stretch goal:
- [ ] Organization profile pages: a page displaying information about the organiser- location, description, images etc. Clicking on the name of the organiser (e.g. Liwan) should take the user to the profile page
